apiVersion: batch/v1
kind: Job
metadata:
  name: guidellm-loadtest
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: guidellm
          image: ghcr.io/vllm-project/guidellm:v0.8.0
          env:
            - name: HF_HUB_CACHE
              value: /tmp/hf_cache
          command:
            - guidellm
            - run
            - --backend
            - kind=openai_http,target=http://llm-d-inference-gateway-istio,model=Qwen/Qwen3-0.6B,request_format=/v1/completions
            - --profile
            - kind=constant,rate=50
            - --constraint
            - kind=max_duration,seconds=3600
            - --data
            - kind=synthetic_text,prompt_tokens=256,output_tokens=512
            - --output
            - kind=json,path=/tmp/results.json
            - --disable-console-interactive
