apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "llm-d-async.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "llm-d-async.labels" . | nindent 4 }}
{{- if .Values.ap.imagePullSecrets }}
imagePullSecrets:
  {{- toYaml .Values.ap.imagePullSecrets | nindent 2 }}
{{- else if .Values.ap.imagePullSecret }}
imagePullSecrets:
  - name: {{ .Values.ap.imagePullSecret }}
{{- end }}
